config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }



  resources :tuitts



  root 'tuitts#index'



  get 'mytuitts', to: 'mytuitts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  # Added this so I can add username and name field to registration form...

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tuitt.rb
class Tuitt < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tuitts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mytuitts_controller.rb
class MytuittsController < ApplicationController

  def index

    @tuitts = Tuitt.where(user_id: current_user.id).order(created_at: :desc)

    @newtuitt = Tuitt.new

  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def new
    super
  end

  def create
    super
  end

  def update
    super
  end

  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/tuitts_controller.rb
class TuittsController < ApplicationController

  before_action :set_article, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create edit update]



  # GET /tuitts
  # GET /tuitts.json

  def index
    @tuitts = Tuitt.all.order(created_at: :desc)
    @newtuitt = Tuitt.new
  end

  # GET /tuitts/1
  # GET /tuitts/1.json

  def show; end

  # GET /tuitts/new

  def new
    @tuitt = Tuitt.new
  end

  # GET /tuitts/1/edit

  def edit
    @newtuitt = Tuitt.new
  end

  # POST /tuitts
  # POST /tuitts.json

  def create
    @tuitt = Tuitt.new(tuitt_params)
    @tuitt.user_id = current_user.id

    respond_to do |format|
      if @tuitt.save
        format.html { redirect_to root_path, notice: 'Tuitt was successfully created.' }
        format.json { render :show, status: :created, location: @tuitt }
      else
        format.html { render :new }
        format.json { render json: @tuitt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tuitts/1
  # PATCH/PUT /tuitts/1.json

  def update
    respond_to do |format|
      if @tuitt.update(tuitt_params)
        format.html { redirect_to root_path, notice: 'Tuitt was successfully updated.' }
        format.json { render :show, status: :ok, location: @tuitt }
      else
        format.html { render :edit }
        format.json { render json: @tuitt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tuitts/1
  # DELETE /tuitts/1.json

  def destroy
    @tuitt.destroy
    respond_to do |format|
      format.html { redirect_to tuitts_url, notice: 'Tuitt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  def my_tuitts
    @tuitts = Tuitt.all.order(created_at: :desc)
    @newtuitt = Tuitt.new
  end

  private

  # Use callbacks to share common setup or constraints between actions.

  def set_article
    @tuitt = Tuitt.find(params[:id])
  end

  # Only allow a list of trusted parameters through.

  def tuitt_params
    params.require(:tuitt).permit(:tuitt)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then 'alert alert-info'
    when :success then 'alert alert-success'
    when :error then 'alert alert-error'
    when :alert then 'alert alert-error'
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand text-white font-weight-bold" href="/" ><h2 class="p-0 m-0">Tuitter</h2></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%# <li class="nav-item active">
        <a class="nav-link text-white" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="#">Tuitt List</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white disabled" href="#" tabindex="-1" aria-disabled="true">Log In</a>
      </li> %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <!-- Button trigger modal -->
      <button type="button" class="btn btn btn-link my-2 my-sm-0 bg-white text-decoration-none" data-toggle="modal" data-target="#exampleModalCenter">
        New Tuitt
      </button>

      <!-- Modal -->
      <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered w-100" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Post a new Tuitt</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <% if user_signed_in? %>
                 <div class="card mb-2 border-0" style="width: 32rem;">
                  <div class="card-body">
                    <div class="float-left mr-4"> 
                    <%= image_tag current_user.gravatar_url, class: "rounded-circle" %>
                    </div>
                    <h6 class="card-title mb-0">Tuitt about it</h5>
                    <div class="blockquote-footer mb-2">Share your thinking with the world!</div>
                    FORM TO TUITT GOES HERE
                  </div>
              </div>
              <% else %>
                <p class="font-weight-bold color-danger">You must be signed in to post.</p>
              <% end %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
      <% if user_signed_in? %>
        <ul class="navbar-nav ml-3">
          <li class="nav-item dropdown">
        <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= edit_user_registration_path %>">Edit Account Details</a>
          <a class="dropdown-item" href="<%= mytuitts_path %>">Just My Tuitts</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="<%= edit_user_registration_path %>">Cancel my account</a>
        </div>
      </li>
        </ul>
        <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "btn btn btn-link my-2 my-sm-0 text-white text-decoration-none" %>
      <% else %>
        <%= link_to 'Log In', new_user_session_path, class: "btn btn btn-link my-2 my-sm-0 text-white text-decoration-none" %>
        <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn btn-link my-2 my-sm-0 text-white text-decoration-none" %>
      <% end %>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BootstrapRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/mytuitts/index.html.erb
<div class="container-fluid">
  <div class="row mt-3">
  <div class="col-3 px-2">
    <% if user_signed_in? %>
    <div class="card bg-light mb-3" style="max-width: 18rem;">
      <div class="card-header">Welcome <%= current_user.name %>!</div>
      <div class="card-body">
        <%= image_tag current_user.gravatar_url, class: "profile-mini-img rounded-circle float-left mr-2" %>
        <h5 class="card-title py-2">@<%= current_user.username %></h5>
        <div class="blockquote-footer text-right"><%= current_user.tuitts.count %> tuitts so far. </div>
      </div>
    </div>
    <% end %>
    <% unless user_signed_in? %><a href="<%= new_user_registration_path %>" class="btn btn-success my-4 btn-block" role="button">Sign Up your Account Here!</a><% end %>
    <table class="table">
      <thead>
        <tr class="thead-light">
          <th scope="col">Trends</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="p-2">Trend 1</td>
        </tr>
        <tr>
          <td class="p-2">Trend 2</td>
        </tr>
        <tr>
          <td class="p-2">Trend 3</td>
        </tr>
      </tbody>
    </table>
  </div>

<div class="col-6">
  
  <% if user_signed_in? %>
  <div class="card mb-2 border-0" style="width: 32rem;">
    
    <div class="card-body">
      <div class="float-left mr-4"> 
      <%= image_tag current_user.gravatar_url, class: "rounded-circle" %>
      </div>
      <h6 class="card-title mb-0">Tuitt about it</h5>
      <div class="blockquote-footer mb-2">Share your thinking with the world!</div>
      <%= form_for @newtuitt do |form| %>
          <% if @newtuitt.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(tuitt.errors.count, "error") %> prohibited this tuitt from being saved:</h2>

          <ul>
            <% @newtuitt.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

        <div class="field">
          <%= form.text_area :tuitt, class: "w-75" %>
        </div>
        
        <div class="actions text-right">
          <%= form.submit "Post Tuitt", class: 'btn btn-primary mr-3'%>
        </div>
      <% end %>
    </div>
  </div>

<% end %>

  <% flash.each do |type, msg| %>
  <div class="alert alert-success alert-dismissible fade show">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
<% end %>


      <% @tuitts.each do |tuitt| %>
        <div class="card mb-2" style="width: 33rem;">
        <div class="card-body">
          <div class="float-left mr-4"> 
          <%= image_tag tuitt.user.gravatar_url, class: "rounded-circle float-left" %>
          </div>
          <h6 class="card-title text-muted"><%= tuitt.user.name %> <% if tuitt.created_at > 1.minutes.ago %><span class="badge badge-warning">Less than a minute ago</span><% end %></h5>
          <h6 class="card-subtitle mb-2"><%= tuitt.tuitt %></h6>
          <div class="blockquote-footer"><%= time_ago_in_words(tuitt.created_at) %> ago by @<%= tuitt.user.username %></div>
          <% if user_signed_in? && current_user.id == tuitt.user_id %>
          <div class="edit-buttons">
            <%= link_to tuitt, class: "text-decoration-none" do %>
            <svg width="1.1em" height="1.1em" viewBox="0 0 16 16" class="bi bi-paperclip" fill="#aaa" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M4.5 3a2.5 2.5 0 0 1 5 0v9a1.5 1.5 0 0 1-3 0V5a.5.5 0 0 1 1 0v7a.5.5 0 0 0 1 0V3a1.5 1.5 0 1 0-3 0v9a2.5 2.5 0 0 0 5 0V5a.5.5 0 0 1 1 0v7a3.5 3.5 0 1 1-7 0V3z"/>
            </svg>
            <% end %>

            <%= link_to edit_tuitt_path(tuitt), class: "text-decoration-none" do %>
            <svg width="1.1em" height="1.1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="#aaa" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
            </svg>
            <% end %>

            <%= link_to tuitt, method: :delete, data: { confirm: 'You will delete the tuitt. Are you sure?' } do %>
            <svg width="1.1em" height="1.1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="#aaa" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
            </svg>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>
      <% end %>
</div>

<div class="col-3 px-2">
    <table class="table">
      <thead>
        <tr class="bg-light">
          <th scope="col">Who to follow</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="p-1">
          <div class="float-left mr-3"> 
          <img src="https://ca.slack-edge.com/T47CT8XPG-U0169L2N13M-110c1739a82f-512" alt="Profile" class="who-to-follow-img rounded-circle">
          </div>
          Ricardo Montenegro
          <div class="blockquote-footer">@ricardo</div>
          </td>
        </tr>
        <tr>
          <td class="p-1">
          <div class="float-left mr-3"> 
          <img src="https://ca.slack-edge.com/T47CT8XPG-U0134FYU848-b2cad07a364f-512" alt="Profile" class="who-to-follow-img rounded-circle">
          </div>
          Kingsley Ibeh
          <div class="blockquote-footer">@kinglsey</div>
          </td>
        </tr>
        <tr>
          <td class="p-1">
          <div class="float-left mr-3"> 
          <img src="https://ca.slack-edge.com/T47CT8XPG-U0168BKD83E-0efe0ebe75bd-512" alt="Profile" class="who-to-follow-img rounded-circle">
          </div>
          Martin Najjar
          <div class="blockquote-footer">@martin</div>
          </td>
        </tr>
        <tr>
          <td class="p-1">
          <div class="float-left mr-3"> 
          <img src="https://ca.slack-edge.com/T47CT8XPG-U013C353RPV-3a65898a98fd-512" alt="Profile" class="who-to-follow-img rounded-circle">
          </div>
          Guillain Bisimwa
          <div class="blockquote-footer">@guillain</div>
          </td>
        </tr>
        <tr>
          <td class="p-1">
          <div class="float-left mr-3"> 
          <img src="https://ca.slack-edge.com/T47CT8XPG-U016MQRTTLP-53d2773bf04d-512" alt="Profile" class="who-to-follow-img rounded-circle">
          </div>
          Andjela Vukadinovic
          <div class="blockquote-footer">@andjela</div>
          </td>
        </tr>
        <tr>
          <td class="p-1">
          <div class="float-left mr-3"> 
          <img src="https://ca.slack-edge.com/T47CT8XPG-U01770QA7A5-d085d5b48db5-512" alt="Profile" class="who-to-follow-img rounded-circle">
          </div>
          Gabriel Suarez
          <div class="blockquote-footer">@gabriel</div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  
</div>

app/views/tuitts/_form.html.erb
<%= form_with(model: tuitt, local: true) do |form| %>
  <% if tuitt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tuitt.errors.count, "error") %> prohibited this tuitt from being saved:</h2>

      <ul>
        <% tuitt.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :tuitt, class: 'w-100 my-4' %>
  </div>

  <div class="actions">
    <%= form.submit "Update Tuitt", class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/tuitts/edit.html.erb
<% if user_signed_in? && @tuitt.user_id == current_user.id %>
  <div class="container my-5">
    <div class="row">
      <div class="col-6 text-center mx-auto">
        <h1>Editing Tuitt</h1>

        <%= render 'form', tuitt: @tuitt %>

        <%= link_to 'Show', @tuitt %> |
        <%= link_to 'Back', root_path %>
      </div>
    </div>
  </div>
<% else %>
  <h2 class="text-danger text-center mt-5"> Your are not allowed to edit this tuitt.</h2>
<% end %>

app/views/tuitts/my_tuitts.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="row">
  <div class="col-3 px-2">
    <table class="table">
      <thead>
        <tr class="thead-light">
          <th scope="col">Trends</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="p-2">Trend 1</td>
        </tr>
        <tr>
          <td class="p-2">Trend 2</td>
        </tr>
        <tr>
          <td class="p-2">Trend 3</td>
        </tr>
      </tbody>
    </table>
  </div>

<div class="col-6">
  

  <div class="card mb-2" style="width: 32rem;">
    <div class="card-body">
      <div class="float-left mr-4"> 
      <img src="https://via.placeholder.com/75" alt="Profile" class="rounded-circle">
      </div>
      <h6 class="card-title mb-0">Tuitt about it</h5>
      <div class="blockquote-footer mb-2">Share your thinking with the world!</div>
      <%= form_for @newtuitt do |form| %>
          <% if @newtuitt.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(tuitt.errors.count, "error") %> prohibited this tuitt from being saved:</h2>

          <ul>
            <% @newtuitt.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

        <div class="field">
          <%= form.text_area :tuitt, class: "w-75" %>
        </div>
        
        <div class="actions text-right">
          <%= form.submit "Post Tuitt", class: 'btn btn-primary mr-3'%>
        </div>
      <% end %>
      </div>
    </div>

      <% @tuitts.each do |tuitt| %>
        <% if tuitt.user.id == current_user.id %>
          <div class="card mb-2" style="width: 32rem;">
          <div class="card-body">
            <div class="float-left mr-4"> 
            <img src="https://via.placeholder.com/75" alt="Profile" class="rounded-circle">
            </div>
            <h6 class="card-title text-muted"><%= tuitt.user.name %></h5>
            <h6 class="card-subtitle mb-2"><%= tuitt.tuitt %></h6>
            <div class="blockquote-footer"><%= time_ago_in_words(tuitt.created_at) %> ago by @<%= tuitt.user.username %></div>
            <div class="edit-buttons">
            <%= link_to tuitt, class: "text-decoration-none" do %>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-paperclip" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M4.5 3a2.5 2.5 0 0 1 5 0v9a1.5 1.5 0 0 1-3 0V5a.5.5 0 0 1 1 0v7a.5.5 0 0 0 1 0V3a1.5 1.5 0 1 0-3 0v9a2.5 2.5 0 0 0 5 0V5a.5.5 0 0 1 1 0v7a3.5 3.5 0 1 1-7 0V3z"/>
            </svg>
            <% end %>

            <%= link_to edit_tuitt_path(tuitt), class: "text-decoration-none" do %>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
            </svg>
            <% end %>

            <%= link_to tuitt, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
            </svg>
            <% end %>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
</div>

<div class="col-3 px-2">
    <table class="table">
      <thead>
        <tr class="bg-light">
          <th scope="col">Who to follow</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="p-1">
          <div class="float-left mr-3"> 
          <img src="https://via.placeholder.com/30" alt="Profile" class="rounded-circle">
          </div>
          Ricardo Montenegro
          <div class="blockquote-footer">@ricardo</div>
          </td>
        </tr>
        <tr>
          <td class="p-1">
          <div class="float-left mr-3"> 
          <img src="https://via.placeholder.com/30" alt="Profile" class="rounded-circle">
          </div>
          Kingsley Ibeh
          <div class="blockquote-footer">@kinglsey</div>
          </td>
        </tr>
        <tr>
          <td class="p-1">
          <div class="float-left mr-3"> 
          <img src="https://via.placeholder.com/30" alt="Profile" class="rounded-circle">
          </div>
          Martin Najjar
          <div class="blockquote-footer">@martin</div>
          </td>
        </tr>
        <tr>
          <td class="p-1">
          <div class="float-left mr-3"> 
          <img src="https://via.placeholder.com/30" alt="Profile" class="rounded-circle">
          </div>
          Guillain Bisimwa
          <div class="blockquote-footer">@guillain</div>
          </td>
        </tr>
        <tr>
          <td class="p-1">
          <div class="float-left mr-3"> 
          <img src="https://via.placeholder.com/30" alt="Profile" class="rounded-circle">
          </div>
          Andjela Vukadinovic
          <div class="blockquote-footer">@andjela</div>
          </td>
        </tr>
        <tr>
          <td class="p-1">
          <div class="float-left mr-3"> 
          <img src="https://via.placeholder.com/30" alt="Profile" class="rounded-circle">
          </div>
          Gabriel Suarez
          <div class="blockquote-footer">@gabriel</div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  
</div>

app/views/tuitts/new.html.erb
<h1>New Tuitt</h1>

<%= render 'form', tuitt: @tuitt %>

<%= link_to 'Back', tuitts_path %>

app/views/tuitts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tuitt message says:</strong>
  <h2><%= @tuitt.tuitt %></h2>
  <h4 class="text-muted">Posted <%= time_ago_in_words(@tuitt.created_at) %> ago by @<%= @tuitt.user.username %></h4>
</p>

<%= link_to 'Edit', edit_tuitt_path(params[:id]) %> |
<%= link_to 'Back', root_path %>